[pytest]
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::UserWarning
    ignore:.*httpx.*
    ignore:.*HTTP_422.*
    ignore:.*StarletteDeprecationWarning.*
