"""Sync DB schema with models

Revision ID: 4e63e6ea078a
Revises: 6b4f34229346
Create Date: 2026-08-05 16:16:44.911322
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e63e6ea078a'
down_revision: Union[str, None] = '6b4f34229346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('total_pills_remaining', sa.Integer(), nullable=False, comment='Current total pills remaining in stock'),
    sa.Column('daily_dose_count', sa.Integer(), nullable=False, comment='Number of pills consumed per day'),
    sa.Column('estimated_refill_date', sa.Date(), nullable=True, comment='AI-predicted date when stock will run out'),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False, comment='Number of days below which a low-stock alert triggers'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refills_id'), 'refills', ['id'], unique=False)
    op.create_index(op.f('ix_refills_medicine_id'), 'refills', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_refills_user_id'), 'refills', ['user_id'], unique=False)
    op.create_table('dose_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False, comment='Date of the scheduled dose'),
    sa.Column('scheduled_time', sa.Time(), nullable=False, comment='Scheduled time of day'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='Taken, Missed, Snooze'),
    sa.Column('action_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snooze_minutes', sa.Integer(), nullable=True, comment='Minutes snoozed if action is Snooze'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dose_logs_action'), 'dose_logs', ['action'], unique=False)
    op.create_index(op.f('ix_dose_logs_id'), 'dose_logs', ['id'], unique=False)
    op.create_index(op.f('ix_dose_logs_medicine_id'), 'dose_logs', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_dose_logs_schedule_id'), 'dose_logs', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_dose_logs_scheduled_date'), 'dose_logs', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_dose_logs_user_id'), 'dose_logs', ['user_id'], unique=False)
    op.alter_column('caregiver_patients', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('medicines', 'disease_category',
               existing_type=postgresql.ENUM('Blood Pressure', 'Diabetes', 'Thyroid', 'Antibiotics', 'Vitamins', 'Heart Medications', 'General Healthcare', name='disease_category'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('medicines', 'dosage',
               existing_type=sa.VARCHAR(length=50),
               comment="e.g., '500mg', '2 Tablets'",
               existing_nullable=False)
    op.alter_column('medicines', 'initial_quantity',
               existing_type=sa.INTEGER(),
               comment='Total quantity when medicine was added/refilled',
               existing_nullable=False)
    op.alter_column('medicines', 'current_stock',
               existing_type=sa.INTEGER(),
               comment='Current remaining quantity',
               existing_nullable=False)
    op.alter_column('medicines', 'daily_frequency',
               existing_type=sa.INTEGER(),
               comment='Number of doses per day',
               existing_nullable=False)
    op.alter_column('medicines', 'quantity_per_dose',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Number of units consumed per dose',
               existing_nullable=False)
    op.alter_column('medicines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('medicines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.add_column('schedules', sa.Column('frequency_pattern', sa.String(length=20), nullable=True, comment="e.g. '1-1-1', '1-0-1', '0-1-1', '0-0-1', or 'custom'"))
    op.add_column('schedules', sa.Column('dose_label', sa.String(length=50), nullable=True, comment="e.g. 'Morning', 'Afternoon', 'Evening', 'Night'"))
    op.alter_column('schedules', 'scheduled_time',
               existing_type=postgresql.TIME(),
               comment='Time of day for this dose, e.g., 08:00',
               existing_nullable=False)
    op.alter_column('schedules', 'day_of_week',
               existing_type=sa.VARCHAR(length=10),
               comment="NULL = everyday, or 'monday', 'tuesday', etc.",
               existing_nullable=True)
    op.alter_column('schedules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('patient', 'caregiver', 'admin', name='user_role'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('patient', 'caregiver', 'admin', name='user_role'),
               server_default=sa.text("'patient'::user_role"),
               existing_nullable=False)
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('schedules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('schedules', 'day_of_week',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment="NULL = everyday, or 'monday', 'tuesday', etc.",
               existing_nullable=True)
    op.alter_column('schedules', 'scheduled_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='Time of day for this dose, e.g., 08:00',
               existing_nullable=False)
    op.drop_column('schedules', 'dose_label')
    op.drop_column('schedules', 'frequency_pattern')
    op.alter_column('medicines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('medicines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('medicines', 'quantity_per_dose',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               comment=None,
               existing_comment='Number of units consumed per dose',
               existing_nullable=False)
    op.alter_column('medicines', 'daily_frequency',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of doses per day',
               existing_nullable=False)
    op.alter_column('medicines', 'current_stock',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Current remaining quantity',
               existing_nullable=False)
    op.alter_column('medicines', 'initial_quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total quantity when medicine was added/refilled',
               existing_nullable=False)
    op.alter_column('medicines', 'dosage',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="e.g., '500mg', '2 Tablets'",
               existing_nullable=False)
    op.alter_column('medicines', 'disease_category',
               existing_type=postgresql.ENUM('Blood Pressure', 'Diabetes', 'Thyroid', 'Antibiotics', 'Vitamins', 'Heart Medications', 'General Healthcare', name='disease_category'),
               server_default=sa.text("'General Healthcare'::disease_category"),
               existing_nullable=False)
    op.alter_column('caregiver_patients', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_dose_logs_user_id'), table_name='dose_logs')
    op.drop_index(op.f('ix_dose_logs_scheduled_date'), table_name='dose_logs')
    op.drop_index(op.f('ix_dose_logs_schedule_id'), table_name='dose_logs')
    op.drop_index(op.f('ix_dose_logs_medicine_id'), table_name='dose_logs')
    op.drop_index(op.f('ix_dose_logs_id'), table_name='dose_logs')
    op.drop_index(op.f('ix_dose_logs_action'), table_name='dose_logs')
    op.drop_table('dose_logs')
    op.drop_index(op.f('ix_refills_user_id'), table_name='refills')
    op.drop_index(op.f('ix_refills_medicine_id'), table_name='refills')
    op.drop_index(op.f('ix_refills_id'), table_name='refills')
    op.drop_table('refills')
    # ### end Alembic commands ###
